# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sp9TYF3Tm2im4tRjQBve4D-tewZEspAB
"""

# Yogyank Entitlement Score


import json
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score, mean_absolute_error
import xgboost as xgb
import joblib


Path = "farmer_scoring_sample_yogyank_round1.csv"

def load_data(path=Path):
    return pd.read_csv(path)

def train_model():
    df = load_data()

    # Removed "defaulted_in_next_12_months"
    categorical_features = ["crop_type", "pm_kisan_status"]
    numeric_features = ["land_area_acres", "historical_repayment_score"]

    features = categorical_features + numeric_features

    x = df[features].copy()
    y = df['target_entitlement_score'].copy()

    # Using shuffle=False
    print("Splitting data (Out-of-Time simulation)...")
    x_train, x_test, y_train, y_test = train_test_split(
        x, y, test_size=0.2, random_state=20, shuffle=False
    )

    print("Preprocessing..")
    preprocessor = ColumnTransformer(transformers=[("num", StandardScaler(), numeric_features),
     ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)])

    model = xgb.XGBRegressor(
        n_estimators=100,
        max_depth=4,
        learning_rate=0.1,
        random_state=20,
        n_jobs=-1,
        tree_method="hist",)

    pipeline = Pipeline(steps=[("preprocessor", preprocessor),("regressor", model)])

    print("Training pipeline...")
    pipeline.fit(x_train, y_train)

    print("Evaluating model...")
    preds = pipeline.predict(x_test)
    r2 = r2_score(y_test, preds)
    mae = mean_absolute_error(y_test, preds)

    print(f"R2 Score: {r2}")
    print(f"MAE: {mae}")

    print("Saving artifacts...")
    joblib.dump(pipeline, "yogyank_scoring_pipeline.pkl")

    schema = {"features": features, "target": 'target_entitlement_score'}
    with open("features.json", "w") as f:
        json.dump(schema, f, indent=4)

    metrics = {"R2": r2, "MAE": mae}
    with open("validation_summary.json", "w") as f:
        json.dump(metrics, f, indent=4)

    print("Artifacts saved")

if __name__ == "__main__":
    train_model()

